import Topic from "../models/Topic.js";
import Question from "../models/Question.js";
import User from "../models/User.js";
import { sequelize } from "../config/db.js";
import { GoogleGenerativeAI } from "@google/generative-ai";
import dotenv from 'dotenv';
dotenv.config();

const genai = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

const getTopics = async (req, res) => {
    try {
        const topics = await Topic.findAll();
        const result = topics.map(t => ({
            id: t.topic_id,
            name: t.name,
            icon: '📚'
        }));
        res.status(200).json(result);
    } catch (error) {
        console.error("Error fetching topics:", error);
        res.status(500).json({ message: "Server Error" });
    }
};

const getQuestions = async (req, res) => {
    try {
        const { topicId } = req.query;
        let limit = parseInt(req.query.limit) || 5;

        if (!topicId) {
            return res.status(400).json({ message: "Missing topicId" });
        }

        const questions = await Question.findAll({
            where: { topic_id: topicId },
            order: sequelize.random(),
            limit: limit
        });

        const formattedQuestions = questions.map((q, index) => {
            const content = q.content || {};
            return {
                id: q.question_id,
                text: content.text || content.question || 'Missing question text',
                options: content.options || [],
                correctIndex: typeof content.correctIndex === 'number' ? content.correctIndex : 0
            };
        });

        res.status(200).json(formattedQuestions);
    } catch (error) {
        console.error("Error fetching questions:", error);
        res.status(500).json({ message: "Server Error" });
    }
};

const singlePlayerResult = async (req, res) => {
    try {
        const { topicId, score } = req.body;
        const userId = req.user.user_id;

        let xpGained = Math.round((Number(score) || 0) / 10);
        xpGained = Math.max(-25, Math.min(75, xpGained));
        
        await User.increment('xp', { by: xpGained, where: { user_id: userId } });
        res.status(200).json({ message: "XP updated", xpGained });
    } catch (error) {
        console.error("Error updating single player result:", error);
        res.status(500).json({ message: "Server Error" });
    }
};

const createQuiz = async (req, res) => {
    try {
        const { title, courseId, difficulty, questions } = req.body;
        const userRole = req.user.role;

        if (userRole !== 'teacher' && userRole !== 'admin') {
            return res.status(403).json({ message: "Unauthorized. Only teachers can create quizzes." });
        }

        if (!title || !questions || !Array.isArray(questions) || questions.length === 0) {
            return res.status(400).json({ message: "Missing required fields or questions array is empty." });
        }

        const newTopic = await Topic.create({
            name: title,
            course_id: courseId || null,
            difficulty_level: difficulty || "medium",
            content: "Quiz generated by teacher"
        });

        const questionsData = questions.map(q => ({
            topic_id: newTopic.topic_id,
            content: {
                text: q.text,
                options: q.options,
                correctIndex: q.correctIndex
            },
            difficulty_level: q.difficulty || difficulty || "medium",
            generated_by_ai: false
        }));

        await Question.bulkCreate(questionsData);

        res.status(201).json({ message: "Quiz created successfully", topic: newTopic });
    } catch (error) {
        console.error("Error creating quiz:", error);
        res.status(500).json({ message: "Server Error" });
    }
};

const generateQuizFromAI = async (req, res) => {
    try {
        const { topicPrompt, difficulty, numQuestions } = req.body;
        const userRole = req.user.role;

        if (userRole !== 'teacher' && userRole !== 'admin') {
            return res.status(403).json({ message: "Unauthorized. Only teachers can use AI generator." });
        }

        if (!topicPrompt) {
            return res.status(400).json({ message: "Missing topic prompt." });
        }

        const count = numQuestions || 5;
        const diff = difficulty || "medium";

        const prompt = `
            You are an expert educator. Generate a multiple-choice quiz based on the following topic or instructions: "${topicPrompt}".
            The difficulty level should be ${diff}.
            Generate exactly ${count} questions.

            Return the output EXCLUSIVELY as a JSON array where each element represents a question.
            Each question object must match this exact structure:
            {
                "text": "The question text",
                "options": ["Option 1", "Option 2", "Option 3", "Option 4"],
                "correctIndex": 0
            }
            The correctIndex must be an integer from 0 to 3 corresponding to the correct option.
            Do not include any formatting, markdown, or text outside of the JSON array.
        `;

        const model = genai.getGenerativeModel({
            model: 'gemini-3-flash-preview',
            systemInstruction: "You are an expert educational planner. Your output must be exactly a valid JSON array matching the requested structure, with no additional formatting or explanations.",
            generationConfig: {
                responseMimeType: "application/json",
            }
        });

        const result = await model.generateContent(prompt);
        let generatedText = result.response.text();

        const startIdx = generatedText.indexOf('[');
        const endIdx = generatedText.lastIndexOf(']');
        if (startIdx !== -1 && endIdx !== -1 && startIdx <= endIdx) {
            generatedText = generatedText.substring(startIdx, endIdx + 1);
        }

        let questions;
        try {
            questions = JSON.parse(generatedText);
        } catch (parseError) {
            console.error("Failed to parse Gemini output as JSON.", parseError);
            return res.status(500).json({ message: "AI returned invalid format. Please try again." });
        }

        res.status(200).json(questions);
    } catch (error) {
        console.error("Error generating AI quiz:", error);
        res.status(500).json({ message: "Server Error" });
    }
};

export { getTopics, getQuestions, singlePlayerResult, createQuiz, generateQuizFromAI };
